/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-10-06 11:14:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>G&amp;Co - La boutique à BD</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<!-- pour les portables et tablettes -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame Remove this if you use the .htaccess -->\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"Philippe\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"lib/img/favicon.ico\" />\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"lib/img/apple-touch-icon.png\" />\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"lib/external/jquery/jquery.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/jquery-ui.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/jquery-ui.structure.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/jquery-ui.theme.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/bootstrap/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/normalize.css\" />\r\n");
      out.write("<script src=\"lib/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Feuilles de style less -->\r\n");
      out.write("<link rel=\"stylesheet/less\" type=\"text/css\" href=\"cfg/app.less\" />\r\n");
      out.write("<!-- <link rel=\"stylesheet/less\" type=\"text/css\" href=\"cfg/menu.less\" /> -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- set options before less.js script -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t/*less = {\r\n");
      out.write("\t\t\tenv: \"development\",\r\n");
      out.write("\t\t\tlogLevel: 2,\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tfileAsync: false,\r\n");
      out.write("\t\t\tpoll: 1000,\r\n");
      out.write("\t\t\tfunctions: {},\r\n");
      out.write("\t\t\tdumpLineNumbers: \"comments\",\r\n");
      out.write("\t\t\trelativeUrls: false,\r\n");
      out.write("\t\t\tglobalVars: {\r\n");
      out.write("\t\t\t\tvar1: '\"string value\"',\r\n");
      out.write("\t\t\t\tvar2: 'regular value'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\trootpath: \":/Cadracnet/\"\r\n");
      out.write("\t\t};*/\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"lib/less/less.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Les scripts de tests / validation -->\r\n");
      out.write("\t<script src=\"img/BD.js\"></script>\r\n");
      out.write("\t<script src=\"img/editors.js\"></script>\r\n");
      out.write("\t<script src=\"lib/HandlersClass.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// Handler document.ready(), initialisation \r\n");
      out.write("\t\t$(document).ready(function(){ var handler = new Handlers(); });\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Image de fond en fade auto -->\r\n");
      out.write("\t<img id=\"t1\" src=\"img/bandeau1-169.jpg\" />\r\n");
      out.write("\t<img id=\"t2\" src=\"img/bandeau2-169.jpg\" />\r\n");
      out.write("\r\n");
      out.write("\t<!--  notre zone de travail -->\r\n");
      out.write("\t<div id=\"t3\" class=\"container-fuild\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- La gestion du login -->\r\n");
      out.write("\t\t<div class=\"container ontop\">\r\n");
      out.write("\t\t\t<div class=\"jumbotron text-center\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div class=\"form-inline login2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"sr-only\" for=\"password\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t<input tabindex=1 type=\"password\" class=\"form-control myshade tglgrp\" id=\"password\" name=\"password\" placeholder=\"Mot de passe\" title=\"Veuillez entrer votre mot de passe\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button tabindex=2 type=\"button\" id=\"login\" class=\"btn btn-primary myshade\" title=\"Je suis là pour vous faire entrer !\">Entrer</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--  <button class=\"hello tgl tglgrp\">Bonjour Charles !</button> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- La barre de boutons -->\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div id=\"biblio\" class=\"row text-center \">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- la gestion des Achat -->\r\n");
      out.write("<!-- \t<div class=\"container-fluid\" id=\"workspace1\">\r\n");
      out.write("\t\t<div class=\"row text-center\">\r\n");
      out.write("\t\tessais de zone\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- La mention légale en bas de page -->\r\n");
      out.write("\t<div class=\"text-center bottom\">\r\n");
      out.write("\t\t<span id=\"cprt\">&copy; 2016 - IMIE Nantes</span>&nbsp;<span id=\"sz\">--</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
